name: NullTerrain
main: uk.me.elizabethmyers.nullterrain.NullTerrain
version: 0.4.2
website: http://elizabethmyers.me.uk/
author: Elizacat
authors: [DjDCH]
description: Terra Nullis for a specific world
load: startup
